---
- hosts: wordpress_nodes
  become: yes
  vars:
    project_name: wordpress
  tasks:
    - name: "Install apache server"
      yum:
        name: httpd
        state: latest
    - name: "Install my sqls"
      yum:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - mariadb
          - mariadb-server
    - name: "Install php"
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
          - php-mysql
          - php
          - MySQL-python
    - name: "Download wp"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - name: "Unarchive wp to destination"
      unarchive: 
        src: /tmp/wordpress.zip
        dest: "/var/www/{{project_name}}"
        remote_src: yes
    - name: "Start service mariadb, if not started"
      service:
        name: mariadb
        state: started
    - name: "Create database"
      mysql_db:
        name: "{{project_name}}"
        state: present
    - name: "Put apache config to the right place"
      copy: 
        src: ./templates/blog.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "Start service httpd, if not started"
      service:
        name: httpd
        state: restarted
    - name: "Copy wp-config"
      copy:
        src: ./templates/wp-config.php
        dest: /var/www/wordpress/wp-config.php